services:
    oro_stylebook.layout.data_provider.style_book_form:
        class: 'Oro\Bundle\StyleBookBundle\Layout\DataProvider\StyleBookFormProvider'
        arguments:
            - '@form.factory'
            - '@router'
        tags:
            - { name: layout.data_provider, alias: style_book_form }

    oro_stylebook.helper.access_helper:
        class: 'Oro\Bundle\StyleBookBundle\Helper\AccessHelper'
        # This service marked as public for compatibility with Symfony 4. All dependencies must be refactored after BAP-17037
        public: true
        arguments:
            - '@service_container'
