services:
    _defaults:
        public: true

    Oro\Bundle\FrontendBundle\Controller\ExceptionController:
        arguments:
            - '@Psr\Container\ContainerInterface'
            - '%kernel.debug%'
        tags:
            - { name: container.service_subscriber }
            - { name: container.service_subscriber, id: 'fos_rest.view_handler' }
            - { name: container.service_subscriber, id: 'fos_rest.exception.codes_map' }

    Oro\Bundle\FrontendBundle\Controller\Workflow\WidgetController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }

    Oro\Bundle\FrontendBundle\Controller\Workflow\WorkflowController:
        calls:
            - ['setContainer', ['@Psr\Container\ContainerInterface']]
        tags:
            - { name: container.service_subscriber }
