parameters:
    oro_platform.collector.template: '@@OroFrontend/Collector/commerce.html.twig'
    oro_attachment.provider.resized_image_path.skip_prefix: 'admin/media/cache'
    oro_frontend.provider.resized_image_path.skip_prefix: 'media/cache'

services:
    oro_frontend.extension.transtation_packages_provider:
        parent: oro_translation.extension.transtation_packages_provider.abstract
        calls:
            - ['addPackage', ['OroCustomerPortal', 'oro/customer-portal', '/src']]
        tags:
            - {name: oro_translation.extension.packages_provider}

    oro_frontend.listener.js_routing_dump:
        class: 'Oro\Bundle\FrontendBundle\EventListener\JsRoutingDumpListener'
        tags:
            - { name: kernel.event_listener, event: console.terminate, method: afterConsoleCommand }

    oro_frontend.listener.frontend_route_collection:
        class: 'Oro\Bundle\FrontendBundle\EventListener\FrontendRouteCollectionListener'
        arguments:
            -
                - oro_translation_jstranslation
        tags:
            - { name: kernel.event_listener, event: oro_distribution.route_collection.expose, method: onCollectionAutoload, priority: 130 }
            - { name: kernel.event_listener, event: oro_distribution.route_collection.autoload, method: onCollectionAutoload, priority: 130 }
        lazy: true

    oro_frontend.listener.route_collection:
        class: 'Oro\Bundle\FrontendBundle\EventListener\RouteCollectionListener'
        arguments:
            - '%web_backend_prefix%'
        tags:
            - { name: kernel.event_listener, event: oro_distribution.route_collection.expose, method: onCollectionAutoload, priority: 120 }
            - { name: kernel.event_listener, event: oro_distribution.route_collection.autoload, method: onCollectionAutoload, priority: 120 }
        lazy: true

    oro_frontend.listener.theme:
        class: 'Oro\Bundle\FrontendBundle\EventListener\ThemeListener'
        arguments:
            - '@oro_theme.registry'
            - '@oro_frontend.request.frontend_helper'
            - '@oro_config.manager'
            - '%installed%'
        tags:
            - {name: kernel.event_listener, event: kernel.request, method: onKernelRequest}
            - {name: kernel.event_listener, event: kernel.view, method: onKernelView, priority: 20 }

    oro_frontend.listener.guest_access_request_listener:
        class: 'Oro\Bundle\FrontendBundle\EventListener\GuestAccessRequestListener'
        arguments:
            - '@oro_security.token_accessor'
            - '@oro_config.manager'
            - '@oro_frontend.guest_access.guest_access_decision_maker'
            - '@router'
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest, priority: 5 }

    oro_frontend.guest_access.guest_access_decision_maker:
        class: 'Oro\Bundle\FrontendBundle\GuestAccess\GuestAccessDecisionMaker'
        arguments:
            - '@oro_frontend.guest_access.provider.chain_guest_access_urls_provider'
            - '@oro_frontend.request.frontend_helper'
            - '%installed%'
        public: false

    oro_frontend.guest_access.provider.guest_access_urls_provider:
        class: 'Oro\Bundle\FrontendBundle\GuestAccess\Provider\GuestAccessAllowedUrlsProvider'
        public: false
        calls:
            - [addAllowedUrlPattern, ['^%oro_api.rest.prefix%']]
        tags: ['oro_frontend.guest_access_urls_provider']

    oro_frontend.placeholder.theme_filter:
        class: 'Oro\Bundle\FrontendBundle\Placeholder\ThemeFilter'
        arguments:
            - '@oro_theme.registry'

    oro_frontend.placeholder.filter:
        class: 'Oro\Bundle\FrontendBundle\Placeholder\FrontendFilter'
        arguments:
            - '@oro_frontend.request.frontend_helper'
            - '@request_stack'

    oro_frontend.request.frontend_helper:
        class: 'Oro\Bundle\FrontendBundle\Request\FrontendHelper'
        arguments:
            - '%web_backend_prefix%'
            - '@service_container'

    oro_frontend.activity_list.placeholder.filter:
        class: 'Oro\Bundle\FrontendBundle\Placeholder\ActivityListPlaceholderFilter'
        arguments:
            - '@oro_activity_list.placeholder.filter'
            - '@oro_frontend.request.frontend_helper'
            - '@request_stack'
        tags:
            - { name: kernel.event_listener, event: oro.ui.grouping_chain_widget.before, method: isAllowedButton, priority: 10 }

    oro_frontend.listener.datagrid.bottom_toolbar:
        class: 'Oro\Bundle\FrontendBundle\EventListener\DatagridBottomToolbarListener'
        arguments:
            - '@oro_frontend.request.frontend_helper'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before, method: onBuildBefore, priority: 10 }

    oro_frontend.listener.datagrid.fields:
        class: 'Oro\Bundle\FrontendBundle\EventListener\DatagridFieldsListener'
        arguments:
            - '@oro_frontend.request.frontend_helper'
        tags:
            # Must be executed before all listeners to disable custom fields
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before, method: onBuildBefore, priority: 255 }

    oro_frontend.listener.update_migration_namespaces:
        class: 'Oro\Bundle\FrontendBundle\CacheWarmer\UpdateNamespacesWarmer'
        arguments:
            - '@oro_frontend.class_migration'
        tags:
            - { name: oro_entity_extend.warmer }

    oro_frontend.class_migration:
        class: 'Oro\Bundle\FrontendBundle\CacheWarmer\ClassMigration'
        arguments:
            - '@doctrine'
            - '@oro_entity_config.config_manager'
            - '%installed%'
        calls:
            - ['append', ['OroB2B', 'Oro']]
            - ['append', ['orob2b', 'oro']]

    oro_frontend.listener.load_class_metadata:
        class: 'Oro\Bundle\FrontendBundle\EventListener\LoadClassMetadataEventListener'
        arguments:
            - '@oro_frontend.class_migration'
        tags:
            - { name: doctrine.event_listener, event: loadClassMetadata }

    oro_frontend.listener.enum_filter_frontend_listener:
        class: 'Oro\Bundle\FrontendBundle\EventListener\EnumFilterFrontendListener'
        arguments:
            - '@oro_frontend.request.frontend_helper'
        tags:
            # Must be executed before all listeners to change route for enum filters
            - { name: kernel.event_listener, event: oro_datagrid.datagrid.build.before, method: onBuildBefore, priority: 255 }

    oro_frontend.provider.current_application:
        class: 'Oro\Bundle\FrontendBundle\Provider\ActionCurrentApplicationProvider'
        decorates: oro_action.provider.current_application
        arguments:
            - '@oro_frontend.provider.current_application.inner'
            - '@security.token_storage'

    oro_frontend.provider.action_route:
        class: 'Oro\Bundle\FrontendBundle\Provider\RouteProvider'
        decorates: oro_action.provider.route
        arguments:
            - '@oro_frontend.provider.action_route.inner'
            - '@security.token_storage'
            - 'oro_frontend_action_widget_form'
            - 'oro_frontend_action_widget_form'
            - 'oro_frontend_action_operation_execute'
            - 'oro_frontend_action_widget_buttons'

    oro_frontend.provider.start_transition_route:
        class: 'Oro\Bundle\FrontendBundle\Provider\RouteProvider'
        decorates: oro_workflow.provider.start_transition_route
        arguments:
            - '@oro_frontend.provider.start_transition_route.inner'
            - '@security.token_storage'
            - 'oro_frontend_workflow_widget_start_transition_form'
            - 'oro_frontend_workflow_start_transition_form'
            - 'oro_api_frontend_workflow_start'
            - 'oro_frontend_workflow_widget_buttons'

    oro_frontend.provider.transition_route:
        class: 'Oro\Bundle\FrontendBundle\Provider\RouteProvider'
        decorates: oro_workflow.provider.transition_route
        arguments:
            - '@oro_frontend.provider.transition_route.inner'
            - '@security.token_storage'
            - 'oro_frontend_workflow_widget_transition_form'
            - 'oro_frontend_workflow_transition_form'
            - 'oro_api_frontend_workflow_transit'
            - 'oro_frontend_workflow_widget_buttons'

    oro_frontend.extension.start_transition_button_provider:
        class: 'Oro\Bundle\FrontendBundle\Extension\FrontendStartTransitionButtonProviderExtension'
        parent: oro_workflow.extension.start_transition_button_provider
        tags:
           - { name: oro.action.extension.button_provider, priority: 110 }

    oro_frontend.extension.transition_button_provider:
        class: 'Oro\Bundle\FrontendBundle\Extension\FrontendTransitionButtonProviderExtension'
        parent: oro_workflow.extension.transition_button_provider
        tags:
           - { name: oro.action.extension.button_provider, priority: 120 }

    oro_frontend.layout_context_configurator.page_template:
        class: 'Oro\Bundle\FrontendBundle\Layout\Extension\PageTemplateContextConfigurator'
        arguments:
            - '@oro_config.global'
        tags:
            - { name: layout.context_configurator }

    oro_frontend.attachment.manager:
        class: 'Oro\Bundle\FrontendBundle\Manager\AttachmentManager'
        parent: 'oro_attachment.manager'

    oro_frontend.attachment.twig.file_extension:
        class: 'Oro\Bundle\FrontendBundle\Twig\FileExtension'
        public: false
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }

    oro_frontend.extractor.frontend_exposed_routes_extractor:
        class: 'Oro\Bundle\FrontendBundle\Extractor\FrontendExposedRoutesExtractor'
        arguments:
            - '@router'
            - []
            - '%kernel.cache_dir%'
            - '%kernel.bundles%'

    oro_frontend.js_routing_controller:
       class: '%fos_js_routing.controller.class%'
       arguments:
            - '@fos_js_routing.serializer'
            - '@oro_frontend.extractor.frontend_exposed_routes_extractor'
            - '%fos_js_routing.cache_control%'
            - '%kernel.debug%'

    oro_frontend.provider.screens:
        class: 'Oro\Bundle\FrontendBundle\Provider\ScreensProvider'
        arguments:
            - '@oro_layout.theme_manager'
            - '@oro.cache.memory_cache_chain'

    oro_frontend.form.configurator.theme:
        class: 'Oro\Bundle\FrontendBundle\Form\Configurator\ThemeConfigurator'
        arguments:
            - '@oro_config.config_bag'
            - '@security.authorization_checker'

    oro_frontend.datagrid.extension.frontend_datagrid:
        class: Oro\Bundle\FrontendBundle\Datagrid\Extension\FrontendDatagridExtension
        arguments:
            - '@security.token_storage'
        tags:
            - { name: oro_datagrid.extension }

    oro_frontend.locale_settings:
        class: Oro\Bundle\FrontendBundle\Model\LocaleSettings
        decorates: oro_locale.settings
        decoration_priority: -10
        arguments:
            - '@oro_frontend.locale_settings.inner'
            - '@oro_frontend.request.frontend_helper'
            - '@oro_frontend_localization.manager.user_localization'

    #  this provider should be run before the last one
    oro_frontend.provider.default_frontend_preferred_language_provider:
        class: Oro\Bundle\FrontendBundle\Provider\DefaultFrontendPreferredLanguageProvider
        public: false
        arguments:
            - '@oro_frontend_localization.manager.user_localization'
            - '@oro_frontend.request.frontend_helper'
        tags:
            - { name: oro_locale.preferred_language_provider, priority: 254 }

    oro_frontend.guest_access.provider.chain_guest_access_urls_provider:
        class: Oro\Bundle\FrontendBundle\GuestAccess\Provider\ChainGuestAccessAllowedUrlsProvider
        arguments: [!tagged oro_frontend.guest_access_urls_provider]

    oro_frontend.listener.authentication:
        class: 'Oro\Bundle\FrontendBundle\EventListener\FrontendLoginListenerDecorator'
        decorates: oro_message_queue.listener.authentication
        arguments:
            - '@kernel'
            - '@oro_frontend.listener.authentication.inner'
            - '@oro_frontend.request.frontend_helper'

    oro_frontend.provider.file_url:
        class: 'Oro\Bundle\FrontendAttachmentBundle\Provider\FileUrlProvider'
        decorates: oro_attachment.provider.file_url
        decoration_priority: 500
        arguments:
            - '@oro_frontend.provider.file_url.inner'
            - '@oro_attachment.url_generator'
            - '@oro_attachment.provider.file_applications'
            - '@oro_action.provider.current_application'
            - '@oro_attachment.acl.file_access_control_checker'
        calls:
            - [setConfigManager, ['@oro_config.manager']]
            - [setFileNameProvider, ['@oro_attachment.provider.attachment_file_name_provider']]

    oro_frontend.provider.resized_image_path.skip_prefix:
        class: 'Oro\Bundle\AttachmentBundle\Provider\ResizedImagePathProviderDecorator'
        decorates: oro_attachment.provider.resized_image_path
        decoration_priority: 100
        arguments:
            - '@oro_frontend.provider.resized_image_path.skip_prefix.inner'
            - '%oro_frontend.provider.resized_image_path.skip_prefix%'

    oro_frontend.event_listener.default_grid_view_load:
        class: Oro\Bundle\FrontendBundle\EventListener\DefaultGridViewLoadListener
        arguments:
            - '@oro_entity.orm.entity_class_resolver'
            - '@oro_search.provider.search_mapping'
            - '@oro_entity_config.config_manager'
            - '@translator'
        tags:
            - { name: kernel.event_listener, event: oro_datagrid.grid_views_load, method: onViewsLoad }

    oro_frontend.twig.frontend:
        class: Oro\Bundle\FrontendBundle\Twig\FrontendExtension
        public: false
        arguments:
            - '@service_container'
        tags:
            - { name: twig.extension }
