dynamic-imports:
    orocommercemenu:
        - orocommercemenu/js/app/views/header-row-view
        - orocommercemenu/js/app/widgets/menu-traveling-widget
    oronavigation:
        - oronavigation/js/app/views/navigation-menu-view
