Oro\Bundle\CommerceMenuBundle\Entity\MenuUpdate:
    group_sequence:
        - MenuUpdate
        - MaxNestedLevel
    constraints:
        - Oro\Bundle\NavigationBundle\Validator\Constraints\MaxNestedLevel:
            groups: [MaxNestedLevel]
    properties:
        titles:
            - Valid: ~
        uri:
            - NotBlank:
                groups: [UserDefined]

            - Oro\Bundle\SecurityBundle\Validator\Constraints\NotDangerousProtocol:
                message: oro.commercemenu.validator.menu_update.not_dangerous_protocol.message

Oro\Bundle\CommerceMenuBundle\Entity\MenuUserAgentCondition:
    properties:
        value:
            - NotBlank: ~
            - Length:
                max: 255
