api:
    entities:
        Oro\Bundle\AddressBundle\Entity\AddressType:
            documentation_resource: '@OroFrontendBundle/Resources/doc/api_frontend/address_type.md'
            filters:
                fields:
                    name:
                        allow_array: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false

        Oro\Bundle\AddressBundle\Entity\Region:
            documentation_resource: '@OroFrontendBundle/Resources/doc/api_frontend/region.md'
            filters:
                fields:
                    combinedCode:
                        allow_array: true
                    country:
                        allow_array: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false

        Oro\Bundle\AddressBundle\Entity\Country:
            documentation_resource: '@OroFrontendBundle/Resources/doc/api_frontend/country.md'
            fields:
                regions:
                    max_results: -1
            filters:
                fields:
                    iso2Code:
                        allow_array: true
            actions:
                create: false
                update: false
                delete: false
                delete_list: false
