entity_config:
    entity:
        entity:
            items:
                frontend_grid_all_view_label:
                    options:
                        translatable:       true
                        priority:           45
                    constraints:
                        - NotBlank:         ~
                        - Length:
                            min:            2
                            max:            55
